### PR TITLE
Add cli support

### PR DESCRIPTION
**Pull request by wesleytodd**
Originally from #14 @helio-frota, looks like the fork was removed, so I just edited here.  Sorry for the really really really long delay.  Let me know what you think of the small changes I made.  I will shoot for merging tomorrow and releasing a `0.2.0`.

### CODE REVIEW

**Comment by wesleytodd** [comment]
Darn, the updated version of `yargs` breaks node@10.  I think that it would be better to drop node@10 support in the cli which is a net new feature, but maybe @ljharb would like to chime in.  This is still pre-1.x, so technically I think we can break here and still be semver compatible.  Once we land these prs and add a few other features from the open issues though I think we can go 1.0 and be more stable.  thoughts?

**Comment by ljharb** [comment]
Every major of yargs tends to drop a node version; i usually just stay on the oldest one that works for me.

**Comment by wesleytodd** [comment]
Also in looking at this we don't yet have docs.  I will open a separate PR for those docs tomorrow.

**Comment by wesleytodd** [comment]
For this case, since it is a new feature, and it doesn't break any of the existing functionality (just the new feature wont work in 10), what do you think? Is it important enough to downgrade since we will be going to 1.x soon (lol I say that after dropping the ball here for over a year, but I really do plan on wrapping it up).

**Comment by ljharb** [comment]
I think it’s fine to launch at v1 supporting whatever is in LTS at that time, which isn’t including node 10.

**Review by helio-frota — APPROVED** [review]
LGTM. And not a problem about the delay, also things/goals/focus changed from my side.
And yeah +1 to drop node 10.x and use LTS versions :slightly_smiling_face:

**Comment by wesleytodd** [comment]
Ok downgraded to `yargs@16` and everything passes.  I will merge this and publish but will push the yargs update along with a 1.x branch.

**Pull request merged**
